# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80a717e0206c3c1249a0f705a68f18ef267b1729064b559f3c27d05c4600eac1be76669b70bf230e2a07f4829358dcbf8430d58d51f4b905a2c244e7300f020d

test:
  secret_key_base: 765bef2d485fbe4a24c328240ae75b3b8e3ef7de2a8fc3e4e909625c3887735fa3f5f3d4d97af60f06140971e5746eefd52880408634d8124c51dacc6f8b36a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
